spring:
  application:
    name: hk-project
  datasource:
    url: jdbc:mysql://localhost:3306/hkproject?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080

logging:
    level:
        com.baomidou.mybatisplus: info

google:
  api-key: AIza